<?php
$title = '404 Page not Found';
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <?php include_once 'includes/meta.php'; ?>
    <?php include_once 'includes/css.php'; ?>
</head>

<body>
    <div class="container py-5 text-center">

        <!-- Main content -->
        <h1 class="display-1 text-warning">404</h1>

        <div class="error-content py-4">
            <h3><i class="fa fa-warning text-warning"></i> Oops! Page not found.</h3>

            <p>
                We could not find the page you were looking for.
                <a href="/">Return to homepage</a>.
            </p>
        </div>

    </div>

    <?php include_once 'includes/js.php'; ?>
</body>

</html>