<?php
$title = '500 Error';
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <?php include_once 'includes/meta.php'; ?>
    <?php include_once 'includes/css.php'; ?>
</head>

<body>
    <div class="container py-5 text-center">

        <!-- Main content -->
        <h1 class="display-1 text-danger">500</h1>

        <div class="error-content py-4">
            <h3><i class="fa fa-warning text-danger"></i> Oops! Something went wrong.</h3>

            <p>
                We will work on fixing that right away.
                <a href="/">Return to homepage</a>.
            </p>
        </div>

    </div>

    <?php include_once 'includes/js.php'; ?>
</body>

</html>