<!DOCTYPE html>
<html lang="id">
    <head>
        <?php include_once 'includes/meta.php'; ?>
        <title>API Test</title>
        <?php include_once 'includes/css.php'; ?>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                /* font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; */
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                /* font-family: 'Lato', sans-serif; */
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1><strong>API</strong> Test</h1>
        <br>

        <div class="" id="app" v-cloak>
            <form @submit.prevent="testAPI()">
                <div class="row mb-3">
                    <div class="form-group offset-3 col-6 text-center">
                        <div class="input-group mb-2">
                            <div class="input-group-prepend">
                                <span class="input-group-text">URL</span>
                            </div>
                            <input class="form-control" id="url" type="text" v-model="url" placeholder="http://api.com/v1">
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Method</span>
                            </div>
                            <select class="form-control" v-model="method">
                                <option value="get">GET</option>
                                <option value="post">POST</option>
                            </select>
                        </div>
                        <div v-for="p, index in params" class="input-group mb-2">
                            <input class="form-control" type="text" v-model="p.key" placeholder="key">
                            <input class="form-control" type="text" v-model="p.value" placeholder="value">
                            <div class="input-group-append">
                                <button class="btn btn-danger" type="button" @click="removeParam(index)">&times;</button>
                            </div>
                        </div>
                        <div class="text-right">
                            <button class="btn btn-info" type="button" @click="addParam()">Add Key</button>
                            <button class="btn btn-success" type="submit">Test API</button>
                        </div>
                    </div>
                </div>
            </form>

            <div class="row">
                <div class="offset-3 col-6">
                    <h2>Result</h2>
                    <pre class="border text-left p-3 bg-light"><code>{{prettyResult}}</code></pre>
                </div>
            </div>
        </div>
    </body>

    <?php include_once 'includes/js.php'; ?>
    <script>

        $(function() {
            $('#url').focus();
        })

        var app = new Vue({
            el: '#app',
            data: {
                url: "http://localhost/platform/v1",
                method: "post",
                params: [],
                result: "result will shown here",
            },
            computed: {
                prettyResult: function() {
                    return JSON.stringify(this.result, null, 2);
                }
            },
            methods: {
                addParam: function() {
                    this.params.push({
                        key: "",
                        value: ""
                    });
                },
                removeParam: function(index) {
                    this.params.splice(index, 1);
                },
                testAPI: function() {
                    let params = {};
                    for (var i=0; i<this.params.length; i++) {
                        params[this.params[i].key] = this.params[i].value;
                    }

                    this.result = 'processing...';

                    $.ajax({
                        url: this.url,
                        method: this.method,
                        data: params
                    })
                    .done(res => {
                        this.result = res;
                    })
                    .fail(err => {
                        this.result = err;
                    })
                }
            }
        })
    </script>
</html>
