<!DOCTYPE html>
<html lang="id">
    <head>
        <?php include_once 'includes/meta.php'; ?>
        <?php include_once 'includes/css.php'; ?>
    </head>
    <body>
        <div class="container" id="app" v-cloak>
            <h1>Tem<strong>plate</strong></h1>
            <p>Hello!</p>
        </div>
    </body>

    <?php include_once 'includes/js.php'; ?>
    <script>
        var app = new Vue({
            el: '#app',
            data: {

            },
            computed: {
                
            },
            methods: {
                
            }
        })
    </script>
</html>
